version: "3.7"

services:

  nzbget:
    image: linuxserver/nzbget:latest
    ports:
      - "6789:6789/tcp"
    env_file:
      - ./common.env
    volumes:
      - type: volume
        source: nzbget-config
        target: /config
      - type: bind
        source: /media/media-lvol0/downloads
        target: /downloads
    networks:
      - download
    deploy:
      restart_policy:
        condition: on-failure
   
  radarr:
    image: linuxserver/radarr:latest
    ports:
      - "7878:7878/tcp"
    env_file:
      - ./common.env
    volumes:
      - type: volume
        source: radarr-config
        target: /config
      - type: bind
        source: /media/media-lvol0/downloads
        target: /downloads
      - type: bind
        source: /media/media-lvol0/Movies
        target: /movies
    networks:
      - download
    deploy:
      restart_policy:
        condition: on-failure
   
  sonarr:
    image: linuxserver/sonarr:latest
    ports:
      - "8989:8989/tcp"
    env_file:
      - ./common.env
    volumes:
      - type: volume
        source: sonarr-config
        target: /config
      - type: bind
        source: /media/media-lvol0/downloads
        target: /downloads
      - type: bind
        source: /media/media-lvol0/TV-Series
        target: /tv
    networks:
      - download
    deploy:
      restart_policy:
        condition: on-failure
   
  bazarr:
    image: linuxserver/bazarr:latest
    ports:
      - "6767:6767/tcp"
    env_file:
      - ./common.env
    volumes:
      - type: volume
        source: bazarr-config
        target: /config
      - type: bind
        source: /media/media-lvol0/Movies
        target: /movies
      - type: bind
        source: /media/media-lvol0/TV-Series
        target: /tv
    networks:
      - download
    deploy:
      restart_policy:
        condition: on-failure

  lidarr:
    image: linuxserver/lidarr:latest
    ports:
      - "8686:8686/tcp"
    env_file:
      - ./common.env
    volumes:
      - type: volume
        source: lidarr-config
        target: /config
      - type: bind
        source: /media/media-lvol0/Music
        target: /music
      - type: bind
        source: /media/media-lvol0/downloads
        target: /downloads
    networks:
      - download
    deploy:
      restart_policy:
        condition: on-failure
  
  ombi:
    image: linuxserver/ombi:latest
    ports:
      - "3579:3579/tcp"
    env_file:
      - ./common.env
    volumes:
      - type: volume
        source: ombi-config
        target: /config
    networks:
      - download
    deploy:
      restart_policy:
        condition: on-failure

volumes:
   nzbget-config:
   radarr-config:
   sonarr-config:
   bazarr-config:
   lidarr-config:
   ombi-config:
networks:
   download:        
