version: '3.7'

services:

  homer:
    image: b4bz/homer:latest
    env_file:
      - ./common.env
    ports:
      - '8088:8080'
    volumes:
      - type: bind
        source: /home/jhrenyk/homer
        target: /www
