version: '3.7'

services:

  homer:
    image: b4bz/homer:latest
    env_file:
      - ./common.env
    ports:
      - '8088:8080'
    volumes:
      - type: bind
        source: /etc/homer/config.yml
        target: /www/config.yml
      - type: bind
        source: /etc/homer/assets
        target: /www/assets
