version: "3.7"

services:
  npm:
    image: jc21/nginx-proxy-manager:2
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - type: volume
        source: nginx-config
        target: /app/config/production.json
      - type: volume
        source: nginx-data
        target: /data
      - type: volume
        source: lets-encrypt
        target: /etc/letsencrypt
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
  db:
    image: jc21/mariadb-aria:10.4
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    env_file:
      - ./common.env
    deploy:
      restart_policy:
        condition: on-failure
    
volumes:
  nginx-config:
  nginx-data:
  mysql-data:
  lets-encrypt:
