version: '3.7'

services:

  npm:
    image: jlesage/nginx-proxy-manager
    env_file:
      - ./common.env
    ports:
      - "81:8181"
      - "80:8080"
      - "443:4443"
    volumes:
      - type: volume
        source: pm-data
        target: /config
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  pm-data:
